language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run --source=coursecake -m pytest --pyargs coursecake
  - coveralls
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
