site_name: CourseCake Docs
site_url: http://docs.coursecake.tisuela.com/

repo_url: https://github.com/nananananate/CourseCake
repo_name: nananananate/CourseCake

theme:
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png

extra:
  disqus: coursecake-docs
